export const TRANSLATIONS = {
  en: {
    nav_features:"Features",nav_platforms:"Platforms",nav_history:"History",nav_login:"Login / Sign Up",
    hero_title:"Download Videos",hero_subtitle:"From Any Platform",
    hero_desc:"Paste any video link from YouTube, TikTok, Instagram, Facebook, or Pinterest. Download in HD quality for free.",
    url_placeholder:"Paste video URL here...",btn_analyze:"Download",supported_on:"Supported:",
    analyzing:"Analyzing your video, please wait...",btn_download_audio:"Download Audio",btn_download_video:"Download Video",
    features_title:"Why Choose VidGrab Pro?",features_subtitle:"Fast, secure, and completely free video downloader",
    feat_fast:"Lightning Fast",feat_fast_desc:"Download videos in seconds with our optimized servers",
    feat_secure:"100% Secure",feat_secure_desc:"No malware, no ads. Your data stays protected",
    feat_free:"Completely Free",feat_free_desc:"No registration required for basic downloads",
    platforms_title:"Supported Platforms",platforms_subtitle:"Download from all major video platforms",
    history_title:"Download History",history_subtitle:"Your recent downloads",
    btn_clear_all:"Clear All",no_history:"No history yet",no_history_desc:"Your downloaded videos will appear here",
    settings_title:"Settings",settings_language:"Language",settings_quality:"Default Quality",settings_format:"Default Format",
    footer_desc:"Free online video downloader.",footer_links:"Quick Links",footer_legal:"Legal",
    footer_privacy:"Privacy Policy",footer_terms:"Terms & Conditions",footer_contact:"Contact",
    footer_copyright:"© 2026 VidGrab Pro. All rights reserved.",nav_home:"Home",
    modal_quality:"Select Quality",quality_note:"Higher quality may take longer to process",
    auth_login:"Login",auth_email:"Email",auth_password:"Password",auth_login_btn:"Login",
    auth_signup:"Sign Up",auth_name:"Name",auth_signup_btn:"Sign Up",
    menu_history:"My History",menu_settings:"Settings",menu_logout:"Logout",
    toast_download_started:"Download started!",toast_login_success:"Login successful!",
    toast_signup_success:"Account created!",toast_logout:"Logged out successfully",
    toast_cleared:"History cleared",toast_deleted:"Item deleted",
    auth_title_login:"Login",auth_title_signup:"Sign Up",
    auth_note:"Login or create a new account with the same form",
    error_analyze:"Failed to analyze video. Please try again.",
    error_download:"Download failed. Please re-analyze the video.",
    how_to_use_title:"How to Use VidGrab Pro",
    step1_title:"Copy URL",step1_desc:"Go to YouTube, TikTok, or Instagram and copy the video link.",
    step2_title:"Paste Link",step2_desc:"Paste the link into the input field above and click Download.",
    step3_title:"Download Video",step3_desc:"Choose your preferred quality format and save the video.",
    error_invalid_url:"Error: This platform is not supported. Please use YouTube, TikTok, Facebook, Instagram, or Pinterest."
  },
  bn: {
    nav_features:"ফিচার",nav_platforms:"প্ল্যাটফর্ম",nav_history:"ইতিহাস",nav_login:"লগইন / সাইন আপ",
    hero_title:"ভিডিও ডাউনলোড করুন",hero_subtitle:"যেকোনো প্ল্যাটফর্ম থেকে",
    hero_desc:"YouTube, TikTok, Instagram, Facebook বা Pinterest থেকে যেকোনো ভিডিও লিঙ্ক পেস্ট করুন।",
    url_placeholder:"ভিডিও URL এখানে পেস্ট করুন...",btn_analyze:"ডাউনলোড",supported_on:"সমর্থিত:",
    analyzing:"আপনার ভিডিও বিশ্লেষণ করা হচ্ছে...",btn_download_audio:"অডিও ডাউনলোড",btn_download_video:"ভিডিও ডাউনলোড",
    features_title:"কেন VidGrab Pro?",features_subtitle:"দ্রুত, নিরাপদ এবং বিনামূল্যে",
    feat_fast:"বজ্রগতি",feat_fast_desc:"সেকেন্ডে ডাউনলোড করুন",
    feat_secure:"১০০% নিরাপদ",feat_secure_desc:"কোনো ম্যালওয়্যার বা বিজ্ঞাপন নেই",
    feat_free:"সম্পূর্ণ বিনামূল্যে",feat_free_desc:"রেজিস্ট্রেশন ছাড়াই ডাউনলোড করুন",
    platforms_title:"সমর্থিত প্ল্যাটফর্ম",platforms_subtitle:"সব প্রধান ভিডিও প্ল্যাটফর্ম থেকে ডাউনলোড",
    history_title:"ডাউনলোড ইতিহাস",history_subtitle:"সাম্প্রতিক ডাউনলোড",
    btn_clear_all:"সব মুছুন",no_history:"কোনো ইতিহাস নেই",no_history_desc:"ডাউনলোড করা ভিডিও এখানে দেখাবে",
    settings_title:"সেটিংস",settings_language:"ভাষা",settings_quality:"ডিফল্ট কোয়ালিটি",settings_format:"ডিফল্ট ফরম্যাট",
    footer_desc:"বিনামূল্যে ভিডিও ডাউনলোডার।",footer_links:"দ্রুত লিঙ্ক",footer_legal:"আইনি",
    footer_privacy:"গোপনীয়তা নীতি",footer_terms:"শর্তাবলী",footer_contact:"যোগাযোগ",
    footer_copyright:"© 2026 VidGrab Pro।",nav_home:"হোম",
    modal_quality:"কোয়ালিটি নির্বাচন",quality_note:"উচ্চ কোয়ালিটিতে বেশি সময় লাগতে পারে",
    auth_login:"লগইন",auth_email:"ইমেইল",auth_password:"পাসওয়ার্ড",auth_login_btn:"লগইন",
    auth_signup:"সাইন আপ",auth_name:"নাম",auth_signup_btn:"সাইন আপ",
    menu_history:"আমার ইতিহাস",menu_settings:"সেটিংস",menu_logout:"লগআউট",
    toast_download_started:"ডাউনলোড শুরু!",toast_login_success:"লগইন সফল!",
    toast_signup_success:"অ্যাকাউন্ট তৈরি হয়েছে!",toast_logout:"লগআউট সফল",
    toast_cleared:"ইতিহাস মুছে গেছে",toast_deleted:"আইটেম মুছে গেছে",
    auth_title_login:"লগইন",auth_title_signup:"সাইন আপ",
    auth_note:"একই ফর্ম দিয়ে লগইন বা অ্যাকাউন্ট তৈরি করুন",
    error_analyze:"ভিডিও বিশ্লেষণ করা যায়নি। আবার চেষ্টা করুন।",
    error_download:"ডাউনলোড ব্যর্থ হয়েছে। পুনরায় অ্যানালাইজ করুন।",
    how_to_use_title:"কীভাবে VidGrab Pro ব্যবহার করবেন",
    step1_title:"URL কপি করুন",step1_desc:"ইউটিউব, টিকটক বা ইনস্টাগ্রামে যান এবং ভিডিও লিংকটি কপি করুন।",
    step2_title:"লিংক পেস্ট করুন",step2_desc:"উপরের ইনপুট বক্সে লিংকটি পেস্ট করুন এবং ডাউনলোড বাটনে ক্লিক করুন।",
    step3_title:"ভিডিও ডাউনলোড করুন",step3_desc:"আপনার পছন্দের ভিডিও কোয়ালিটি সিলেক্ট করে ডাউনলোড সম্পন্ন করুন।",
    error_invalid_url:"ত্রুটি: এই প্ল্যাটফর্ম সমর্থিত নয়। YouTube, TikTok, Facebook, Instagram বা Pinterest ব্যবহার করুন।"
  },
  hi: {
    nav_features:"विशेषताएं",nav_platforms:"प्लेटफॉर्म",nav_history:"इतिहास",nav_login:"लॉगिन / साइन अप",
    hero_title:"वीडियो डाउनलोड करें",hero_subtitle:"किसी भी प्लेटफ़ॉर्म से",
    hero_desc:"YouTube, TikTok, Instagram से लिंक पेस्ट करें। मुफ्त HD डाउनलोड।",
    url_placeholder:"वीडियो URL यहाँ पेस्ट करें...",btn_analyze:"डाउनलोड",supported_on:"समर्थित:",
    analyzing:"विश्लेषण हो रहा है...",btn_download_audio:"ऑडियो डाउनलोड",btn_download_video:"वीडियो डाउनलोड",
    features_title:"VidGrab Pro क्यों?",features_subtitle:"तेज़, सुरक्षित और मुफ्त",
    feat_fast:"बिजली की गति",feat_fast_desc:"सेकंड में डाउनलोड",
    feat_secure:"100% सुरक्षित",feat_secure_desc:"कोई मैलवेयर नहीं",
    feat_free:"पूरी तरह मुफ्त",feat_free_desc:"बिना रजिस्ट्रेशन के",
    platforms_title:"समर्थित प्लेटफ़ॉर्म",platforms_subtitle:"सभी प्लेटफ़ॉर्म से डाउनलोड",
    history_title:"डाउनलोड इतिहास",history_subtitle:"हाल के डाउनलोड",
    btn_clear_all:"सभी साफ करें",no_history:"कोई इतिहास नहीं",no_history_desc:"डाउनलोड यहाँ दिखेंगे",
    settings_title:"सेटिंग्स",settings_language:"भाषा",settings_quality:"डिफ़ॉल्ट गुणवत्ता",settings_format:"डिफ़ॉल्ट प्रारूप",
    footer_desc:"मुफ्त ऑनलाइन वीडियो डाउनलोडर।",footer_links:"त्वरित लिंक",footer_legal:"कानूनी",
    footer_privacy:"गोपनीयता नीति",footer_terms:"नियम",footer_contact:"संपर्क",
    footer_copyright:"© 2026 VidGrab Pro।",nav_home:"होम",
    modal_quality:"गुणवत्ता चुनें",quality_note:"उच्च गुणवत्ता में समय लग सकता है",
    auth_login:"लॉगिन",auth_email:"ईमेल",auth_password:"पासवर्ड",auth_login_btn:"लॉगिन",
    auth_signup:"साइन अप",auth_name:"नाम",auth_signup_btn:"साइन अप",
    menu_history:"मेरा इतिहास",menu_settings:"सेटिंग्स",menu_logout:"लॉगआउट",
    toast_download_started:"डाउनलोड शुरू!",toast_login_success:"लॉगिन सफल!",
    toast_signup_success:"खाता बनाया!",toast_logout:"लॉगआउट सफल",
    toast_cleared:"इतिहास साफ",toast_deleted:"आइटेम हटाया",
    auth_title_login:"लॉगिन",auth_title_signup:"साइन अप",
    auth_note:"लॉगिन या नया खाता बनाएं",
    error_analyze:"विश्लेषण विफल। पुनः प्रयास करें।",
    error_download:"डाउनलोड विफल।",
    how_to_use_title:"VidGrab Pro का उपयोग कैसे करें",
    step1_title:"यूआरएल कॉपी करें",step1_desc:"यूट्यूब, टिकटॉक या इंस्टाग्राम पर जाएं और वीडियो लिंक कॉपी करें।",
    step2_title:"लिंक पेस्ट करें",step2_desc:"ऊपर दिए गए इनपुट बॉक्स में लिंक पेस्ट करें और डाउनलोड पर क्लिक करें।",
    step3_title:"वीडियो डाउनलोड करें",step3_desc:"अपनी पसंदीदा वीडियो गुणवत्ता चुनें और डाउनलोड करें।",
    error_invalid_url:"त्रुटि: यह प्लेटफ़ॉर्म समर्थित नहीं है। YouTube, TikTok, Facebook, Instagram या Pinterest का उपयोग करें।"
  },
  es: {
    nav_features:"Características",nav_platforms:"Plataformas",nav_history:"Historial",nav_login:"Iniciar sesión / Registro",
    hero_title:"Descargar Videos",hero_subtitle:"De Cualquier Plataforma",
    hero_desc:"Pega el enlace de YouTube, TikTok, Instagram, etc. Descarga gratis en HD.",
    url_placeholder:"Pega la URL aquí...",btn_analyze:"Descargar",supported_on:"Compatible:",
    analyzing:"Analizando...",btn_download_audio:"Descargar Audio",btn_download_video:"Descargar Video",
    features_title:"¿Por qué VidGrab Pro?",features_subtitle:"Rápido, seguro y gratuito",
    feat_fast:"Ultra Rápido",feat_fast_desc:"Descarga en segundos",
    feat_secure:"100% Seguro",feat_secure_desc:"Sin malware ni anuncios",
    feat_free:"Completamente Gratis",feat_free_desc:"Sin registro requerido",
    platforms_title:"Plataformas",platforms_subtitle:"Todas las principales plataformas",
    history_title:"Historial",history_subtitle:"Descargas recientes",
    btn_clear_all:"Limpiar Todo",no_history:"Sin historial",no_history_desc:"Tus descargas aparecerán aquí",
    settings_title:"Configuración",settings_language:"Idioma",settings_quality:"Calidad Predeterminada",settings_format:"Formato Predeterminado",
    footer_desc:"Descargador de videos gratuito.",footer_links:"Enlaces",footer_legal:"Legal",
    footer_privacy:"Privacidad",footer_terms:"Términos",footer_contact:"Contacto",
    footer_copyright:"© 2026 VidGrab Pro.",nav_home:"Inicio",
    modal_quality:"Seleccionar Calidad",quality_note:"Mayor calidad tarda más",
    auth_login:"Iniciar sesión",auth_email:"Correo",auth_password:"Contraseña",auth_login_btn:"Iniciar sesión",
    auth_signup:"Registrarse",auth_name:"Nombre",auth_signup_btn:"Registrarse",
    menu_history:"Mi Historial",menu_settings:"Configuración",menu_logout:"Cerrar sesión",
    toast_download_started:"¡Descarga iniciada!",toast_login_success:"¡Sesión iniciada!",
    toast_signup_success:"¡Cuenta creada!",toast_logout:"Sesión cerrada",
    toast_cleared:"Historial borrado",toast_deleted:"Eliminado",
    auth_title_login:"Iniciar sesión",auth_title_signup:"Registrarse",
    auth_note:"Inicia sesión o regístrate",
    error_analyze:"Análisis fallido. Intenta de nuevo.",error_download:"Descarga fallida.",
    how_to_use_title:"Cómo usar VidGrab Pro",
    step1_title:"Copiar URL",step1_desc:"Ve a YouTube, TikTok o Instagram y copia el enlace del video.",
    step2_title:"Pegar enlace",step2_desc:"Pega el enlace en el campo de arriba y haz clic en Descargar.",
    step3_title:"Descargar video",step3_desc:"Elige tu calidad preferida y guarda el video.",
    error_invalid_url:"Error: Esta plataforma no es compatible. Use YouTube, TikTok, Facebook, Instagram o Pinterest."
  }
};

export const ALLOWED_URL_PATTERNS = [
  /^https?:\/\/(www\.)?(youtube\.com|youtu\.be)\/.+/i,
  /^https?:\/\/(www\.|m\.)?facebook\.com\/.+/i,
  /^https?:\/\/fb\.watch\/.+/i,
  /^https?:\/\/(www\.)?instagram\.com\/.+/i,
  /^https?:\/\/(www\.|vm\.)?tiktok\.com\/.+/i,
  /^https?:\/\/(www\.)?pinterest\.(com|co\.\w{2})\/.+/i,
  /^https?:\/\/pin\.it\/.+/i
];
